// ============================================================
// POST /api/deliver — MCP / GitHub Delivery Endpoint (Gap #5)
// Pushes generated files to a new GitHub repository.
// GitHub token stored in request body (from client localStorage).
// ============================================================

import { NextRequest, NextResponse } from 'next/server';

interface GitHubDeliveryConfig {
  token: string;
  owner: string;
  repoName: string;
  description?: string;
  private?: boolean;
}

interface GeneratedFile {
  path: string;
  content: string;
}

async function pushToGitHub(
  config: GitHubDeliveryConfig,
  files: GeneratedFile[]
): Promise<{ repoUrl: string; commitSha: string }> {
  const headers = {
    Authorization: `token ${config.token}`,
    'Content-Type': 'application/json',
    Accept: 'application/vnd.github.v3+json',
    'User-Agent': 'Multi-Agent-Orchestrator/2.0',
  };

  const baseUrl = 'https://api.github.com';

  // 1. Create repository
  const createRepoRes = await fetch(`${baseUrl}/user/repos`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: config.repoName,
      description: config.description || 'Generated by Multi-Agent Orchestrator',
      private: config.private ?? false,
      auto_init: true,
    }),
  });

  if (!createRepoRes.ok) {
    const err = await createRepoRes.json();
    throw new Error(`Failed to create repository: ${err.message || JSON.stringify(err)}`);
  }

  const repo = await createRepoRes.json();
  const repoUrl: string = repo.html_url;

  // Wait for repo initialization
  await new Promise(r => setTimeout(r, 2500));

  // 2. Get default branch SHA
  const refRes = await fetch(
    `${baseUrl}/repos/${config.owner}/${config.repoName}/git/refs/heads/main`,
    { headers }
  );

  if (!refRes.ok) throw new Error('Failed to get main branch ref');
  const ref = await refRes.json();
  const latestSha: string = ref.object.sha;

  // 3. Create blobs for all files
  const blobShas = await Promise.all(
    files.map(async (file) => {
      const blobRes = await fetch(
        `${baseUrl}/repos/${config.owner}/${config.repoName}/git/blobs`,
        {
          method: 'POST',
          headers,
          body: JSON.stringify({
            content: Buffer.from(file.content).toString('base64'),
            encoding: 'base64',
          }),
        }
      );
      if (!blobRes.ok) throw new Error(`Failed to create blob for ${file.path}`);
      const blob = await blobRes.json();
      return { path: file.path, sha: blob.sha };
    })
  );

  // 4. Create tree
  const treeRes = await fetch(
    `${baseUrl}/repos/${config.owner}/${config.repoName}/git/trees`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify({
        base_tree: latestSha,
        tree: blobShas.map(b => ({
          path: b.path,
          mode: '100644',
          type: 'blob',
          sha: b.sha,
        })),
      }),
    }
  );

  if (!treeRes.ok) throw new Error('Failed to create tree');
  const tree = await treeRes.json();

  // 5. Create commit
  const commitRes = await fetch(
    `${baseUrl}/repos/${config.owner}/${config.repoName}/git/commits`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify({
        message: '🤖 Generated by Multi-Agent Orchestrator\n\nAuto-generated code, tests, and deployment configs.',
        tree: tree.sha,
        parents: [latestSha],
      }),
    }
  );

  if (!commitRes.ok) throw new Error('Failed to create commit');
  const commit = await commitRes.json();

  // 6. Update branch reference
  const updateRefRes = await fetch(
    `${baseUrl}/repos/${config.owner}/${config.repoName}/git/refs/heads/main`,
    {
      method: 'PATCH',
      headers,
      body: JSON.stringify({ sha: commit.sha }),
    }
  );

  if (!updateRefRes.ok) throw new Error('Failed to update branch reference');

  return { repoUrl, commitSha: commit.sha };
}

export async function POST(req: NextRequest) {
  try {
    const { target, config, files } = await req.json();

    if (!target) {
      return NextResponse.json({ error: 'Missing target field (e.g. "github")' }, { status: 400 });
    }

    if (!files || !Array.isArray(files) || files.length === 0) {
      return NextResponse.json({ error: 'No files provided for delivery' }, { status: 400 });
    }

    if (target === 'github') {
      if (!config?.token || !config?.owner || !config?.repoName) {
        return NextResponse.json(
          { error: 'GitHub config requires: token, owner, repoName' },
          { status: 400 }
        );
      }

      const result = await pushToGitHub(config as GitHubDeliveryConfig, files as GeneratedFile[]);
      return NextResponse.json({ success: true, ...result });
    }

    return NextResponse.json({ error: `Unknown delivery target: ${target}` }, { status: 400 });

  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Delivery failed';
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
